version: '3.8'

name: generic-json

services:
  flask_app:
    build: ./generic-json
    ports:
      - "80:80"
    volumes:
      - ./generic-json/:/app/

networks:
  open-forms-dev:
    name: open-forms-dev
